name: Bug (v2)
description: Create an issue using the bug report template.
title: "[BUG] <title here>"
labels: ["bug"]

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: >
        Short summary of what's happening (1–3 sentences).
        You can include links to external context (e.g., Slack, Sentry, Notion),
        but still summarize the issue clearly.

  - type: textarea
    id: steps
    attributes:
      label: Steps To Reproduce
      description: >
        List of steps or explanation to reproduce the issue, including environment details
        (e.g., OS, browser, latest/beta).

  - type: textarea
    id: actual_result
    attributes:
      label: Actual Result
      description: What happens when reproducing the issue.

  - type: textarea
    id: expected_result
    attributes:
      label: Expected Result
      description: What should happen / why the actual result is incorrect.

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: >
        (Optional) Attach or link screenshots, screen recordings, or other
        helpful context that might aid investigation.

  - type: textarea
    id: lessons_learned
    attributes:
      label: Lessons Learned
      description: >
        Fill in after investigation - Any improvements, process changes,
        or documentation to prevent similar issues in the future.
