name: Bug
description: Create an issue using the bug report template.
title: "[BUG] <title here>"
labels: ["bug"]
type: Bug

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: >
        Short summary of what's happening (1–3 sentences). 
        You can include links to external context (e.g., Slack, Sentry, Notion),
        but still summarize the issue clearly.
      placeholder: e.g., "When clicking 'Save', the app crashes with a 500 error."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps To Reproduce
      description: >
        List the steps to reproduce the issue, including environment details 
        (e.g., OS, browser, app version, beta vs stable).
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: actual_result
    attributes:
      label: Actual Result
      description: What happens when reproducing the issue.
      placeholder: e.g., "App crashes with 500 error."
    validations:
      required: true

  - type: textarea
    id: expected_result
    attributes:
      label: Expected Result
      description: What should happen (and why the actual result is incorrect).
      placeholder: e.g., "App should save changes without errors."
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: >
        (Optional) Attach or link screenshots, screen recordings, or other
        helpful context that might aid investigation.
      placeholder: e.g., "Screenshot of console error message."
    validations:
      required: false

  - type: textarea
    id: lessons_learned
    attributes:
      label: Lessons Learned
      description: >
        (Optional, for post-investigation) Any improvements or process changes
        to prevent similar issues in the future.
      placeholder: e.g., "Add monitoring for X; clarify deployment checklist."
    validations:
      required: false
